### ISSUE TITLE
Model weights already trained

### ISSUE THREAD

**Issue by IgorMunizS** [hmchuong/ML-BoneSuppression#1]
Hi,
I know its not a issue, but can you share your model weights (already trained)?
I'm trying a new approach and I would like something to compare.
Thanks!

**Comment by suryatejadev** [comment]
+1

**Comment by hmchuong** [comment]
There is still some issue with my code and I will give you my trained weight soon

**Comment by gusers** [comment]
@hmchuong  Did your code work?

**Comment by Ouwen** [comment]
https://github.com/hmchuong/ML-BoneSuppression/blob/f9a73249cb9d61c2135bb5e3138b24b3bdae19c1/model.py#L55

should this be stride [1,1,1,1] instead?

**Comment by Ouwen** [comment]
Seems like according to the paper:

"The type of each layer of our architectures is convolutional.
Size of the filters used for convolution remains the same for
all of the models and layers: 5 × 5. The strides of AE-like
model are [1, 2, 2, 1], and the strides of CNN family models are
[1, 1, 1, 1]. "

Should the AE-like model encoding step get rid of the max pool step and increase stride to [1,2,2,1]?

**Comment by Ouwen** [comment]
Also I was wondering, is there any reason the tensorflow ms-ssim op cannot be used?
https://www.tensorflow.org/api_docs/python/tf/image/ssim_multiscale

**Comment by hmchuong** [comment]
I have updated the version 2 of this project, now, you can use my pretrained model

**Comment by hmchuong** [comment]
> Also I was wondering, is there any reason the tensorflow ms-ssim op cannot be used?
> https://www.tensorflow.org/api_docs/python/tf/image/ssim_multiscale

I have updated this function in new version
